// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCuvdm4wel8SQnQcmIYy-9q4KqkIwXh1o',
    appId: '1:143322629160:web:3b776846b05f3fbc39211d',
    messagingSenderId: '143322629160',
    projectId: 'arriada-group-352e1',
    authDomain: 'arriada-group-352e1.firebaseapp.com',
    storageBucket: 'arriada-group-352e1.appspot.com',
    measurementId: 'G-0S7T9C3FSG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwE7xpJJVjBV30eAxuduSqsc5De2qXwG4',
    appId: '1:143322629160:android:92986f0ffc2e696139211d',
    messagingSenderId: '143322629160',
    projectId: 'arriada-group-352e1',
    storageBucket: 'arriada-group-352e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWxF8-4xFnQhvsfHPCq3_vqOzlNzCX_Ss',
    appId: '1:143322629160:ios:c4bf93a6dd57a2ff39211d',
    messagingSenderId: '143322629160',
    projectId: 'arriada-group-352e1',
    storageBucket: 'arriada-group-352e1.appspot.com',
    iosClientId: '143322629160-j2ebh2p3of668del3a8ubelvhun9tlc0.apps.googleusercontent.com',
    iosBundleId: 'com.example.arriadaGroup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWxF8-4xFnQhvsfHPCq3_vqOzlNzCX_Ss',
    appId: '1:143322629160:ios:c4bf93a6dd57a2ff39211d',
    messagingSenderId: '143322629160',
    projectId: 'arriada-group-352e1',
    storageBucket: 'arriada-group-352e1.appspot.com',
    iosClientId: '143322629160-j2ebh2p3of668del3a8ubelvhun9tlc0.apps.googleusercontent.com',
    iosBundleId: 'com.example.arriadaGroup',
  );
}
